### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by nobodyshere** [nobodyshere/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by greedydwarf222** [comment]
1967
At the age of 17, I was sentenced to three years incarceration for participating in a robbery and assault. Everyone makes mistakes :)

1971
I married Lyudmyla (née Nastenko), a niece of Yenakiyeve city judge Oleksandr Sazhyn. 

1974 
Was enrolled at the Donetsk Polytechnic Institute. Yay!

2002–2004
President Leonid Kuchma appointed me to the post of Prime Minister following Anatoliy Kinakh's resignation. 
I began my term as Prime Minister on 21 November 2002 following a 234-vote confirmation in the Verkhovna Rada, eight more than needed. 

In foreign affairs, my cabinet was considered to be politically close to Russia, although declaring support for Ukrainian membership in the European Union. Although my parliamentary coalition was not supporting Ukrainian membership in the North Atlantic Treaty Organization (NATO), my cabinet agreed to the commission of Ukrainian troops to the Iraq War in support of the United States' War on Terrorism.

2004 

In 2004, as the Prime Minister, I participated in the controversial Ukrainian presidential election as the Party of Regions candidate. My main base of support emerged from the southern and eastern regions of Ukraine, which favor close ties with neighbouring Russia. In the first round of voting held on 31 October 2004, I took second place with 39.3 percent of the votes to opposition leader Viktor Yuschenko with 39.8 percent. Because no candidate passed the 50 percent threshold, a second round of voting was scheduled. In the second round of the election, I was initially declared the winner. However, the legitimacy of the election was questioned by many Ukrainians, international organizations, and foreign governments following allegations of electoral fraud. The second round of the election was subsequently annulled by the Supreme Court of Ukraine, and in the repeated run-off, I was lost to Yushchenko.

2005
 The Party of Regions signed a collaboration agreement with the Russian political party United Russia. In 2008, I spoke at a congress of the United Russia party.
 
2007
I was assigned the post of appointed chairman of the Government Chiefs Council of the Commonwealth of Independent States.

2009
I announced my intent to run for President in the upcoming presidential election. I was endorsed by the Party of Regions and the Youth Party of Ukraine.
I called for my supporters go to Maidan Nezalezhnosti Kiev's Independence Square in case of election fraud.
Early vote returns from the first round of the election held on 17 January showed me in first place with 35.8% of the vote. I faced a 7 February 2010 runoff against Tymoshenko, who finished second (with 24.7% of the vote). After all ballots were counted, the Ukrainian Central Election Commission declared that I won the runoff election with 48.95% of the vote compared with 45.47% for Tymoshenko. Tymoshenko withdrew her subsequent legal challenge of the result.

2010–2014
Somehow became a president of Ukraine. 

2014
Left Ukraine for some time to visit my friends in Russia.
